deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master
env:
  global:
    secure: fim0X6OrKVc2aqaThd0ElWjgdnfNz8bc99fI6ZMh2g0l6caIaDZorNli5Z+JX4k/WdCzUcAmVMMHud8yDqcMfjRYknrQwfRpEO0HHQU32uv67TfH0lg9V3lyFanXJCTNhu4FpaiYpu59j/JhHcyHrfGZ2tovoe0xvatAKq3oZ8yY2iGi4IYGa6fEl20BgqWE3+7+AIdJR4K4V6G2dLYXeLEqvKz6W7s2zxm8Bf4IkR54zVorpOxxCC7kuYyoM7p94OxT46caL1lrIRHvgjnY9frQ3OBgOwnitqO8mBRuTTjsOfBSdrZ7dVaHVHPlSQYC/lMubEZWTNfHJ4lQ+e7WWmxrEk9ZFTnn+mbm+FNQADVGU4qWViufCHioG5gC51xX64idH6q5FhpB24Py1PjRx8gcWFh3N6hit1SDf3ZlN7qZzjpPoKz8aLEF5/rICnWH+FNCHKbaMkwWoN86zGfezJbA4lV6dCiPlX3mJarVWJydNouPWn6HPtPDh0nAiQJgGlenGp0VHn0VqrSRqY6fiQCnSf1YqDEcycC1ui/Kz/w5NJ31iY2Hcocel6j23WhZkbLeUP/01Kcm/sGzBSMkwCGGxwG3TEczLGVVOhACFL9PtOQIvUEhKN/hMMBqHcu2ebyLTWaBvVhiYOW96P2nfwxZQ17HIrN550tODypMdfU=
