language: node_js
node_js:
- 6.11.3
before_install:
- npm i -g npm@5.6.0
deploy:
  provider: script
  skip_cleanup: true
  script: bash ./scripts/deploy.sh
  on:
    branch: master
env:
  global:
  - secure: NyE/gAdppJQO+De+46EPm2IsfpjEvdWhwbEm/0/JA4Q7As1XdQMc9XmM/tLHPHV005w0ugXLLfQKHO+mlhkzGv0UTrimvLg8hCeocy4Aeg9nF7NcfG1YSuys9KKx9T/Xf4g5OGrjmkqOYNUVH3bNG1UZ7FvWMBfMmNR5h3nhB1cgSsbj7T2Q4OpKoyDE+jXp0dCgXMCm+G5/HfssPDj9GnAiPgzhozTLg/oz1/XuhX/NaTiNA5BXNvvKWMQLRP9bMPlJxZiwHWs4Ez81D5kUq9UC5f7ww8/xSoAFDSY/awdU51n50YVA7iLBCtxlDMrkRixElLqnWxIwSJXYt9WNLnxCrO8gFXKJahb9ybEJo7vWuJ6ed3y3f3548Z/wNreq7Or6OuugmIqSnBC57ME9DJfmiswuMBFWVyZYq6gMsHOg4NHZ33/bKDNS8PE4wI5ITtOkM4KRiydJx6P3S/yGEcBcAsLyN/iGqNeWHzJbmfBi8ioWxY6X5AHQcEavr586CB4Ala1+GEMv3ogJtgISmi6IY7Zm/3cvXpbRW5933hIZnxgehF3EZ+EGL1CbQkeZtFYs69Rkrwf+6SEfhMZcgDLnsd4u3A+G+2KN9eX3380tz21PkipCFe9ZawdhKJgP7EROtRYndJVn4QgY72I+TgG1HlPRfqEWYCtizvEFdC4=
